spring:
  main:
    banner-mode: off
    log-startup-info: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_api
    username: root
    password:
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update
  sql:
    init:
      encoding: UTF-8
      mode: never
      schema-locations: classpath:schema.sql
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent-output: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  output:
    ansi:
      enabled: always
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: -1
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

management:
  endpoints:
    web:
      base-path: /admin
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          EnumType: trace
          descriptor:
            sql:
              BasicBinder: trace

setting:
  content-type: "text/csv"
  extension: ".csv"
