version: "3.8"

services:
  mysql-server:
    image: mysql:5.7
    container_name: "java-restful-api-db"
    hostname: "java-restful-api-db"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "java_api"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
    networks:
      - container-network

networks:
  container-network:
    name: java-restful-api
