openapi: 3.0.3
info:
  description: 商品情報を管理するAPIです。
  version: 1.0.0
  title: Java-RESTful-API
servers:
  - url: http://localhost:8080/api/v1
    description: ローカルサーバ
tags:
  - name: Product
    description: 商品の情報を管理する
  - name: Csv
    description: CSVファイル関連

paths:
  /products:
    $ref: './paths/products.yml'
  /products/{id}:
    $ref: './paths/products-id.yml'
  /csv/upload:
    $ref: './paths/csv-upload.yml'
  /csv/download:
    $ref: './paths/csv-download.yml'

components:
  schemas:
    $ref: './components.yml'
