name: OpenAPI Docs Build and Deploy to Netlify

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Workspace
        uses: actions/checkout@v3

      - name: Set up Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install redoc
        run: npm install -g redoc-cli

      - name: Build openAPI file
        run: redoc-cli build ./docs/swagger.yml --options.expandResponses=all --options.pathInMiddlePanel -o ./docs/index.html

      - name: Deploy to netlify
        run: npx netlify-cli deploy --dir=./docs
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
